### ISSUE TITLE
Does this project support multiple GPU training ?

### ISSUE THREAD

**Issue by za970120604** [megvii-research/AAAI2023-PVD#2]
Sorry for bothering again , 
does this project support multiple GPU training ? 
if not , what arguments can I modify to avoid OOM ?
(I just find --max_ray_batch in main_just_train_tea.py) , 
thanks a lot !

**Comment by Fangkang515** [comment]
Here is some ways that may reduce the memory cost:
1. Reduce the value of parameter '--num_rays' .
2. Try to disable the parameter of '--preload'. When preload=True, it will load all image data into the gpu. For images with large resolution, it will occupy memory seriously (But I haven't tested this parameter, which is inherited from torch-ngp).
3. If you don't have too strict requirements for image resolution, you can use the downsampled image for experiment.
4. In the distillation process, due to the need to load the student and the teacher network at the same time, it will consume more memory. One solution is to separately inference the teacher network in advance and record the data required for distillation, and use these data to guide the training of the student.
5. For different model(INGP/Plenoxels/NeRF/TensoRF), there are different parameters to adjust the model size. For example, you can reduce the number and resolution of hash tables in INGP, reduce the resolution of Plenoxels or tensoRF, and reduce the number of MLP parameters in NeRF, etc.
6. The current code does not support multi-GPUs temporarily, but it should be easy to implement. If the above cannot solve your problem, you can try to implement DDP.
