### ISSUE TITLE
Ask about llff dataset

### ISSUE THREAD

**Issue by a1445605672** [megvii-research/AAAI2023-PVD#3]
Hi, my test results on the synthetic dataset are good. But I tested on the official llff dataset and found that the effect is not good, in the llff_data/flower directory, my result is only 2.93.

**Comment by Fangkang515** [comment]
I would like to ask what is the downsampling multiple you use on llff datasets? I suggest debugging from a lower downsampling (like 8x downsampling).

In addition, for the result of 2.93, I think it is the problem of parameter setting. The parameters of our code can be inherited from the [torch-ngp](https://github.com/ashawkey/torch-ngp/tree/3b066b6cd6ccd3610cb66a56a54f5daaf12a8033) , which provides a visual parameter adjustment interface that may help you find the right parameters quickly.

For forward facing data LLFF, some important parameters are as follows:
--bound
--scale 

For 4x downsample on flower scenes, bound=10 and scale=0.03 would be a better choice.

**Comment by a1445605672** [comment]
Thank you, I have modified the code according to your suggestion, and the effect is very good. In addition, I noticed that you have published the PVD-AL paper. I am continuing to follow up. May I ask how many days the code can be updated?

**Comment by Fangkang515** [comment]
Thanks for your following.
I am currently busy with an another work at hand. According to the plan, I will release the PVD-AL code within a month (about 20 days). 
I will keep this issue open and inform you here once the PVD-AL code is released.

**Comment by a1445605672** [comment]
Thank you, I encountered the following error during the distillation phase after modifying the parameters as per your suggestion. Have you ever encountered this issue before?
![image](https://user-images.githubusercontent.com/41555798/233004198-df9f4954-c910-43a8-80cc-53827e57d7be.png)

**Comment by Fangkang515** [comment]
It seems that the network parameters you used for training the teacher are inconsistent with the teacher parameters used for distillation. 
If you have no problem training on synthetic dataset, you may check the difference between the two experimental settings

**Comment by a1445605672** [comment]
Hi, I have now been able to successfully distill students using a model trained with 4x downsampling. But I am running on a single 3090 graphics card, the resource usage rate is 100%, the speed is very slow, and there is a memory overflow. Is there something wrong with my parameter settings?
![image](https://user-images.githubusercontent.com/41555798/233236639-cbb6ef15-4d22-43d6-a140-d17dff36ca6c.png)
![image](https://user-images.githubusercontent.com/41555798/233236505-ad7df5b5-cc06-4928-bac3-129f09759842.png)
![image](https://user-images.githubusercontent.com/41555798/233238291-fdd0833f-c012-4fb1-9687-e8f31a7c01f2.png)

**Comment by Fangkang515** [comment]
My experiment was conducted on v100 and I haven't encountered this situation yet. For the llff dataset, 4X downsampling still has a relatively high resolution. The best way for 24G memory GPU is to reduce the downsampling factor, such as 8x.

(**PS**. During distillation, both the teacher and student are loaded into the GPU, which consumes more memory compared to training a network alone. This may be a limitation where our method can be further improved. If you are interested in breaking through this limitation, you can try to improve it.)


Off course, here is some other ways that may reduce the memory cost easily:


-  Reduce the value of parameter '--num_rays' .

- Try to disable the parameter of '--preload'. When preload=True, it will load all image data into the gpu. For images with large resolution, it will occupy memory seriously (But I haven't tested this parameter, which is inherited from torch-ngp).

- If you don't have too strict requirements for image resolution, you can use the downsampled image for experiment.
In the distillation process, due to the need to load the student and the teacher network at the same time, it will consume more memory. One solution is to separately inference the teacher network in advance and record the data required for distillation, and use these data to guide the training of the student.

- For different model(INGP/Plenoxels/NeRF/TensoRF), there are different parameters to adjust the model size. For example, you can reduce the number and resolution of hash tables in INGP, reduce the resolution of Plenoxels or tensoRF, and reduce the number of MLP parameters in NeRF, etc.

**Comment by a1445605672** [comment]
Hello, I tested my own dataset and found that the rendered video is very blurry, and the PSNR is not very high, but the same algorithm works better with instant-NGP. Could it be that there is a problem with my parameter settings?

![image](https://user-images.githubusercontent.com/41555798/233817447-24d283d5-3454-4f24-9bb5-0a6889bd706c.png)
![image](https://user-images.githubusercontent.com/41555798/233817396-83c67ace-3b80-4e9f-b385-b62d6bcc6c20.png)

**Comment by Fangkang515** [comment]
Yes, this is the problem of  parameter settings. Since the parameter setting in the real scene is not automatic (from [torch-ngp](https://github.com/ashawkey/torch-ngp)), you need to adjust the --bound and --scale parameters. 

Usually you can train a few steps, using the dichotomy quickly adjust one of the parameters, like --bound，

**Comment by Fangkang515** [comment]
Hi, I have update the code of PVDAL: https://github.com/megvii-research/AAAI2023-PVD/tree/PVD-AL

If you have any questions, please feel free to contact me at any time.
